spring:
  application:
    name: ribbon

server:
  port: 3001

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka

ribbon:
  # \u5355\u53F0\u670D\u52A1\u5668\u91CD\u8BD5\u6B21\u6570(\u4E0D\u5305\u62EC\u521D\u6B21)
  MaxAutoRetries: 1
  # \u5207\u6362\u4E0B\u53F0\u670D\u52A1\u5668\u91CD\u8BD5\u6B21\u6570
  MaxAutoRetriesNextServer: 2

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500

#hystrix dashboard
management:
  endpoints:
    web:
      exposure:
        include: "*"